# ASP.NET Core



# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  git_commit: $(Build.SourceVersion)

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '$(Build.SourcesDirectory)/Nvg.API.SMS/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: 'latest'
    repository: 'nvgapisms'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      cd ~
      wget https://github.com/digitalocean/doctl/releases/download/v1.58.0/doctl-1.58.0-linux-amd64.tar.gz
      tar xf ~/doctl-1.58.0-linux-amd64.tar.gz
      sudo mv ~/doctl /usr/local/bin
      doctl
      word=$(git_commit)
      set version = "$(echo $word | cut -c1-8)"
      echo $version
      docker tag nvgapisms registry.digitalocean.com/tv2/nvgapisms:$(version)
      docker push registry.digitalocean.com/tv2/nvgapisms:$(version)
      echo 'Hello world'

      
