trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  git_commit: $(Build.SourceVersion)
  image_name: 'nvgapisms'

steps:
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '$(Build.SourcesDirectory)/Nvg.SMSBackgroundTask/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: 'latest'
    repository: '$(image_name)'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      cd ~
      wget https://github.com/digitalocean/doctl/releases/download/v1.58.0/doctl-1.58.0-linux-amd64.tar.gz
      tar xf ~/doctl-1.58.0-linux-amd64.tar.gz
      sudo mv ~/doctl /usr/local/bin
      doctl auth init -t cf9b816121903f8101d96c9d73a36ae6716b42d4902a23f2c5d1f1a8b3f5f17c
      doctl registry login
      word=$(git_commit)
      ver=$(echo $word | cut -c1-8)
      echo $ver
      #docker tag $(image_name) registry.digitalocean.com/tv2/$(image_name):$ver
      #docker push registry.digitalocean.com/tv2/$(image_name):$ver